### ISSUE TITLE
Cannot parse def f((x, y))?

### ISSUE THREAD

**Issue by lebigot** [ankurdave/color-identifiers-mode#29] opened 2015-03-14 12:56 UTC
A definition like:

```
def f((x, y)):
…
```

trips color-identifiers-mode with:

```
Error running timer `color-identifiers:refresh': (wrong-type-argument symbolp (x (\, y)))
```

This is too bad, since it breaks the nice identifier coloring of the whole file!

**Comment by ankurdave** [comment] 2017-06-15 20:53
`color-identifiers:python-get-declarations` still can't handle tuple parameter unpacking, but since we now don't crash and instead just leave those parameters uncolored, I think that's good enough to mark this issue resolved.

**Comment by lebigot** [comment] 2017-06-16 06:42
There is no crash, but the rest of the file loses its coloring! That's quite a big issue, that would warrant to leave this one open, no?

**Comment by ankurdave** [comment] 2017-06-16 07:15
Oh, that didn't happen when I tried it. [Here's what my test looks like](https://cdn.rawgit.com/ankurdave/6669f51b035b30c769cb2c2edc3873ea/raw/dd8c481886fe6b8cd720a11cd1ef0f298ae46a70/test-py.html). Could you post an example when you get the chance?

**Comment by Hi-Angel** [comment] 2023-01-09 05:51
Neither can I reproduce it. I mean, adding a 

```
def f((x, y)):
    pass
```

doesn't result in any error for me. I also tried making a lambda in a similar way, to no avail.

The `x`, `y` ain't highlighted though, but that's because it's not a valid python syntax, a python interpreter trips over it. So I presume the only problem was that `color-identifiers` was failing with an error, but that isn't happening anymore. Either it was fixed, or some important information is missing.

Therefore, I'm closing it, but feel free to reopen if you find a reproducer.

**Closed by Hi-Angel** 2023-01-09 05:51 UTC

**Comment by Hi-Angel** [comment] 2023-01-09 05:56
In terms of a proof:

![image](https://user-images.githubusercontent.com/7935057/211248200-029bbd33-785c-46df-9178-da9e08f78d4c.png)

**Comment by Hi-Angel** [comment] 2023-01-09 06:35
I should note separately that I can't seem to find a way to make `global-color-identifiers-mode` fail when a `color-identifiers-mode` fails in a buffer.
